# Generated by Django 3.1 on 2020-09-28 19:50

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='url',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='filename',
            field=models.CharField(default='default', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='default', upload_to=portfolio.models.ProjectImage.get_path),
            preserve_default=False,
        ),
    ]
