# Generated by Django 3.1 on 2020-09-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200928_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='filename',
        ),
    ]
