# Generated by Django 3.1 on 2020-10-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200930_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
