# Generated by Django 3.1 on 2020-10-30 19:33

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projectimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
